name: Dev Check (React + Node)

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install backend
        run: |
          cd server
          npm ci

      - name: Install frontend
        run: |
          cd client
          npm ci

      - name: Build frontend
        run: |
          cd client
          npm run build
